export const mainData = [
    { key: "Total Users", value: 153 },
    { key: "Total Rides", value: 1587 },
    { key: "Total Revenue", value: 10734 },
    { key: "Total Owners", value: 163 },
];

export const rideData = [
    { key: "Active Users", value: 246 },
    { key: "Active Rides", value: 125 },
    { key: "Flaged Rides", value: 21 },
    { key: "Emergency", value: 3 },
];

export const ridesData = [
    {
      rideId: "1",
      carOwner: "Jeevansh Ahuja",
      carOwnerContact: "9876543210",
      riders: ["Rider1", "Rider2"],
      rideStatus: "In Progress",
      rideStart: "2021-09-20 10:00:00",
      rideEnd: "",
      startPlace: "Delhi",
      endPlace: "Noida",
      progress: "62",
      securityStatus: "Safe",
      farePerPerson: "200",
    },
    {
      rideId: "2",
      carOwner: "Aryan Verma",
      carOwnerContact: "9876541230",
      riders: ["Rider3"],
      rideStatus: "In Progress",
      rideStart: "2021-09-19 15:30:00",
      rideEnd: "2021-09-19 16:30:00",
      startPlace: "Gurgaon",
      endPlace: "Faridabad",
      progress: "78",
      securityStatus: "Safe",
      farePerPerson: "300",
    },
    {
      rideId: "3",
      carOwner: "Mehak Sharma",
      carOwnerContact: "9123456789",
      riders: ["Rider4", "Rider5", "Rider6"],
      rideStatus: "Cancelled",
      rideStart: "2021-09-18 09:00:00",
      rideEnd: "",
      startPlace: "Noida",
      endPlace: "Delhi",
      progress: "0",
      securityStatus: "Stage1",
      farePerPerson: "150",
    },
    {
      rideId: "4",
      carOwner: "Rishabh Gupta",
      carOwnerContact: "9876543220",
      riders: ["Rider7", "Rider8"],
      rideStatus: "In Progress",
      rideStart: "2021-09-21 08:45:00",
      rideEnd: "",
      startPlace: "Lucknow",
      endPlace: "Kanpur",
      progress: "45",
      securityStatus: "Stage 3",
      farePerPerson: "250",
    },
    {
      rideId: "5",
      carOwner: "Aditi Jain",
      carOwnerContact: "9876501234",
      riders: ["Rider9", "Rider10"],
      rideStatus: "In Progress",
      rideStart: "2021-09-22 12:00:00",
      rideEnd: "",
      startPlace: "Pune",
      endPlace: "Mumbai",
      progress: "34",
      securityStatus: "Safe",
      farePerPerson: "400",
    },
    {
      rideId: "6",
      carOwner: "Ankit Tiwari",
      carOwnerContact: "9876548765",
      riders: ["Rider11"],
      rideStatus: "In Progress",
      rideStart: "2021-09-20 07:30:00",
      rideEnd: "2021-09-20 08:45:00",
      startPlace: "Jaipur",
      endPlace: "Ajmer",
      progress: "68",
      securityStatus: "Safe",
      farePerPerson: "350",
    },
    {
      rideId: "7",
      carOwner: "Priya Singh",
      carOwnerContact: "9876541212",
      riders: ["Rider12", "Rider13", "Rider14"],
      rideStatus: "In Progress",
      rideStart: "2021-09-21 11:00:00",
      rideEnd: "",
      startPlace: "Chennai",
      endPlace: "Bangalore",
      progress: "70",
      securityStatus: "Safe",
      farePerPerson: "500",
    },
    {
      rideId: "8",
      carOwner: "Vikram Khurana",
      carOwnerContact: "9876547890",
      riders: ['Rider15'],
      rideStatus: "In Progress",
      rideStart: "2021-09-23 18:00:00",
      rideEnd: "",
      startPlace: "Hyderabad",
      endPlace: "Vijayawada",
      progress: "0",
      securityStatus: "Safe",
      farePerPerson: "350",
    },
  ];

export const UnsafeRides=[
  {
    rideId: "4",
    carOwner: "Rishabh Gupta",
    carModel:"Swift",
    carOwnerContact: "9876543220",
    riders: ["Rider7", "Rider8"],
    rideStatus: "In Progress",
    rideStart: "2021-09-21 08:45:00",
    rideEnd: "",
    startPlace: "Lucknow",
    endPlace: "Kanpur",
    progress: "45",
    securityStatus: "Stage 2",
    farePerPerson: "250",
    distanceRemaining: "100",
    duration: "2",
  },
  {
    rideId: "5",
    carOwner: "Aditi Jain",
    carOwnerContact: "9876501234",
    riders: ["Rider9", "Rider10"],
    rideStatus: "In Progress",
    rideStart: "2021-09-22 12:00:00",
    rideEnd: "",
    startPlace: "Pune",
    endPlace: "Mumbai",
    progress: "56",
    securityStatus: "Stage 2",
    farePerPerson: "400",
    
  },
  {
    rideId: "6",
    carOwner: "Ankit Tiwari",
    carOwnerContact: "9876548765",
    riders: ["Rider11"],
    rideStatus: "In Progress",
    rideStart: "2021-09-20 07:30:00",
    rideEnd: "2021-09-20 08:45:00",
    startPlace: "Jaipur",
    endPlace: "Ajmer",
    progress: "89",
    securityStatus: "Stage 2",
    farePerPerson: "350",
  },
]
export const passengers=[
  {
    rideId: "5",
    carOwner: "Aditi Jain",
    carOwnerContact: "9876501234",
    riders: ["Rider9", "Rider10"],
    rideStatus: "In Progress",
    rideStart: "2021-09-22 12:00:00",
    rideEnd: "",
    startPlace: "Pune",
    endPlace: "Mumbai",
    progress: "56",
    securityStatus: "Stage 2",
    farePerPerson: "400",
    
  },
  {
    rideId: "6",
    carOwner: "Ankit Tiwari",
    carOwnerContact: "9876548765",
    riders: ["Rider11"],
    rideStatus: "In Progress",
    rideStart: "2021-09-20 07:30:00",
    rideEnd: "2021-09-20 08:45:00",
    startPlace: "Jaipur",
    endPlace: "Ajmer",
    progress: "89",
    securityStatus: "Stage 2",
    farePerPerson: "350",
  },
]


  

  
